### ISSUE TITLE
Python Library

### ISSUE THREAD

**Issue by kbenrafik** [sparkfun/SparkFun_BNO08x_Arduino_Library#1]
### Subject of the issue
I’m looking for the same library but for Python

### Your workbench
* What development board or microcontroller are you using? Jetson Orin/Nano
* What version of hardware or breakout board are you using? 
* How is the breakout board to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by lewispg228** [comment]
Hi @kbenrafik ,
Sorry for the very delayed response here. Thank you for submitting this issue, however, due to the fact that our library is built on top of the fairly large SH2 Driver, we will not be able to create a python version of our library at this time.

If you'd like to submit an issue on the [SH2 driver repository](https://github.com/ceva-dsp/sh2/issues) requesting a python version, then perhaps this might be a good place to start.
