### ISSUE TITLE
Issue with SAMD51 on Windows 

### ISSUE THREAD

**Issue by gigapod** [sparkfun/SparkFun_BNO08x_Arduino_Library#8]
### Subject of the issue
From a customer review - issue using this library with SAMD51

#### the review comment
I ran into an issue with the SparkFun_BNO08x_Arduino_Library.h. I am using the SparkFun Thing Plus SAMD51 and if you upload any of the sample programs windows will notify you that the USB device is not recognized and you will not be able to use the serial monitor to view the serial console for the SAMD51.

I was able to solve the issue if you move the #include <Wire.h> to after the #include "SparkFun_BNO08x_Arduino_Library.h". I am not 100% sure why this is but I would assume it has to do with something in the SparkFun_BNO08x_Arduino_Library.h. Hope this helps anyone that runs into this problem.

**Comment by lewispg228** [comment]
Thanks @gigapod , Looks like this customer also posted an issue here: 

[https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library/issues/6](https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library/issues/6) 

Although, they seem to have found a work-around, it seems strange that moving the location of the "#include <Wire.h>" would change much. 

I intend to try this out with actual hardware next week and hope to get to the root cause. 

Either way, once a solution is in place, I will be sure to follow up on the github issue and the storefront product comment.
